### ISSUE TITLE
document the difference about the LowRes.7z and the MKD_Plugin.7z

### ISSUE THREAD

**Issue by asmwarrior** [DawidPi/MKD51-Simulator#2]
Hi, you should at least write some words about what does those binary packages means?
My guess is that the former one's panel is much smaller?

**Comment by asmwarrior** [comment]
OK, I see it described in wiki now. Great!

**Comment by asmwarrior** [comment]
I think you need to add the wiki link in the homepage's README.md file.

**Comment by DawidPi** [comment]
Yes you are right. I did this already :+1:
